---

#
# This file contains configuration flags to customize this site
#

# Name of the site (displayed in the content)
name: Ben Leggiero's Résumé
# Name of the site (displayed in the tab)
title: Ben Leggiero's Résumé

# Short bio or description (in share links)
description: >
    Senior Software Engineer &amp; Architect with a passion for designing &amp;
    making great products

author:
    name: Ben Leggiero
    # URL of the avatar or profile pic
    avatar: >
        https://www.gravatar.com/avatar/2f4691f7a1c9d3192fe843a164a27535?s=280px

    social:
        email: BenLeggiero@Gmail.com
        linkedin: ben-leggiero
        github: BenLeggiero/resumes
        twitter: BenLeggiero
        stackoverflow: users/3939277/ben-leggiero
        website: https://BenLeggiero.me

# # Enter the Google Analytics web tracking code (e.g. UA-2110908-2) to
# # activate tracking
# google_analytics:

# This website URL
# Used for Sitemap.xml and the RSS feed
url: https://Resume.BenLeggiero.me

# If this site is hosted at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

timezone: America/Denver


# Low-level config lines #


permalink: /:title/

# The release of Jekyll Now that this site is using
version: v3.8.5

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
    style: :expanded  # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
    - jekyll-sitemap  # Create a sitemap using the official Jekyll sitemap gem
    - jekyll-feed  # Create an Atom feed using the official Jekyll feed gem
    - jekyll-archives
    - jekyll-redirect-from  # Allow multiple names for a page

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - CNAME
